terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted

return code: 134
